<a href="https://colab.research.google.com/github/wanutchapornmun/229352-StatisticalLearning/blob/main/Lab08_Pytorch_660510561.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [ ]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [ ]:
a= torch.tensor(2)
a

tensor(2)

### Convert a tensor to scalar

In [ ]:
b= torch.tensor(3)
a * b

tensor(6)

### Creating 2D tensor

In [ ]:
c = b.item() # เปลี่ยน tensor เป็นตัวเลข
c

3

In [ ]:
A = torch.tensor([[1, 2],[5,6]])
A

tensor([[1, 2],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

### Convert from numpy array to tensor

In [ ]:
B = A.numpy()
B

array([[1, 2],
       [5, 6]])

## PyTorch and GPU

check if GPU is available

In [ ]:
torch.cuda.is_available()

True

In [ ]:
C = torch.from_numpy(B) #array to tensor
C

tensor([[1, 2],
        [5, 6]])

## Basic operations

In [ ]:
C * 2

tensor([[ 2,  4],
        [10, 12]])

In [ ]:
C - 2

tensor([[-1,  0],
        [ 3,  4]])

In [ ]:
C * np.array([1, 2])

/tmp/ipython-input-4026174697.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  C * np.array([1, 2])


tensor([[ 1,  4],
        [ 5, 12]])

### Matrix multiplication

การคูณกัน

In [ ]:
A = torch.tensor([[4, 5], [8, 9]])
B = torch.tensor([[1, 4], [7, 8]])

torch.matmul(A, B) # เวลาเอาไปใช้จริงอย่าลืมตั้งชื่อด้วย

tensor([[ 39,  56],
        [ 71, 104]])

In [ ]:
torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [ ]:
# ใช้บ่อยสุด (จำง่ายสุด)
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [ ]:
A

tensor([[4, 5],
        [8, 9]])

In [ ]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [ ]:
a = torch.zeros(1, 2, 3) # ด้านใน zeros จะเป็นมิติของ array ในที่นี้จะเป็น tensor 3 มิติ
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
I = torch.eye(3) # จำนวนแถวหรือคอลัมน์ของเมทริกซ์
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
R1 = torch.rand(2, 3)
R1 # ตัวเลขที่ได้จะเป็นการสุ่มแบบ uniform

tensor([[0.2504, 0.9190, 0.4200],
        [0.1056, 0.5817, 0.6603]])

In [ ]:
R2 = torch.randn(2, 3) # n = normal destribution
R2

tensor([[ 0.5937, -0.1936,  0.4884],
        [-0.5497, -0.1000, -1.2072]])

In [ ]:
a = torch.arange(6) # คำสั่งในการสร้างเวกเตอร์
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

### Checking the shape of a tensor

In [ ]:
A.shape

torch.Size([2, 2])

In [ ]:
A.size() # เป็น method ต้องใส่วงเล็บให้ด้วย

torch.Size([2, 2])

### Changing the shape of a tensor

In [ ]:
u = torch.arange(6)
u.shape

torch.Size([6])

In [ ]:
v = u.reshape(2, 3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
w = u.view(3, 2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

stack จะเป็นการเพิ่ม dimension

In [ ]:
a = torch.arange(4)
b = torch.arange(4) + 1

c = torch.stack([a, b], axis=0)
c # เอาเวกเตอร์ a กับ b มาต่อกัน

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [ ]:
d = torch.stack([a, b], axis=1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [ ]:
# concatenate
e = torch.cat([a, b], axis=0)
e # output ที่ได้มิติก็ยังเท่าเดิมอยู่

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [ ]:
f = torch.cat([a, b], axis=1)
f # จะ error เพราะมีแค่มิติที่ 0 ไม่มีมิติ 1

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### Squeezing a tensor (removing an extra dimension)

In [ ]:
A = torch.zeros(1, 2, 3)
B = A.squeeze() # จะเอาแกนแรกออกไป
B # แกนจะหายไป จะเหลือแค่แกนที่ 2 กันแกนที่ 3

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
B.shape

torch.Size([2, 3])

### Unsqueezing a tensor (adding an extra dimension)

In [ ]:
# H.shape = (6, )
C = B.unsqueeze(axis=0) # จะขยายที่แกนแรก (axis=0)
C # จะเห็นว่ามีวงเล็บซ้อนกัน 3 ชั้น ดังนั้นจึงเป็น tensor 3 มิติ เช็คขนาดดูได้

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
C.shape

torch.Size([1, 2, 3])

## Indexing

In [ ]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [ ]:
# วิธีการทำ index
P[[0, 1, 2], [0, 1, 2]] # list ของแถวและคอลัมน์ที่จะดึงมา
P[0:3, 0:3]

tensor([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]])

In [ ]:
A ** 2

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
A.sum()

tensor(0.)

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [ ]:
# 1. Create three random  N(0,1)  tensors
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

# 2. Create a tensor that contains only 1's with shape (200, 1)
ones = torch.ones(200, 1)

# 3. Modify tensor X by adding the tensor in 2. as the first column
X = torch.cat([ones, X], axis=1)

# 4. Compute y
y = X @ b + e

# 5.
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)
b_hat = torch.inverse(X.T @ X) @ X.T @ y

# 6
y_hat = X @ b_hat

# 7
y = y.numpy()
y_hat = y_hat.numpy()

mse = 1 / 200 * np.sum(y - y_hat) ** 2
print("MSE =", mse)

MSE = 1.0260237e-13


In [ ]:
X1 = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X2 = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[ 1.0000,  0.4979, -0.3224,  ...,  0.6333,  2.1876,  0.3152],
        [ 1.0000,  2.0087,  1.0637,  ..., -1.6947,  1.6150,  1.0191],
        [ 1.0000,  0.5215, -1.1181,  ..., -0.8956, -1.0726,  1.8177],
        ...,
        [ 1.0000,  0.4653, -0.6585,  ..., -0.6831,  0.4401, -0.1209],
        [ 1.0000, -1.8634,  1.4632,  ..., -0.0182,  0.8742, -1.5814],
        [ 1.0000,  0.0996, -0.7735,  ...,  0.6058, -0.1343,  0.4743]])
tensor([[ 1.0000,  0.4979, -0.3224,  ...,  0.6333,  2.1876,  0.3152],
        [ 1.0000,  2.0087,  1.0637,  ..., -1.6947,  1.6150,  1.0191],
        [ 1.0000,  0.5215, -1.1181,  ..., -0.8956, -1.0726,  1.8177],
        ...,
        [ 1.0000,  0.4653, -0.6585,  ..., -0.6831,  0.4401, -0.1209],
        [ 1.0000, -1.8634,  1.4632,  ..., -0.0182,  0.8742, -1.5814],
        [ 1.0000,  0.0996, -0.7735,  ...,  0.6058, -0.1343,  0.4743]])


In [ ]:
X1.shape

torch.Size([3, 3])

In [ ]:
X2.shape

torch.Size([3, 4])

In [ ]:
X1 = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
b1 = torch.randn(4,1)
e1 = torch.randn(3,1)
ones1 = torch.ones(3, 1)
X1 = torch.cat([ones1, X1], axis=1)
y1 = X1 @ b1 + e1
b_hat1 = torch.inverse(X1.T @ X1) @ X1.T @ y1
y_hat1 = X1 @ b_hat1

y1 = y1.numpy()
y_hat1 = y_hat1.numpy()

mse1 = 1 / 200 * np.sum(y1 - y_hat1) ** 2
print("MSE =", mse1)

MSE = 0.3508712


In [ ]:
X2 = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]], dtype=torch.float32)
b2 = torch.randn(4,1)
e2 = torch.randn(3,1)
y2 = X2 @ b2 + e2
b_hat2 = torch.inverse(X2.T @ X2) @ X2.T @ y2
y_hat2 = X2 @ b_hat2

y2 = y2.numpy()
y_hat2 = y_hat2.numpy()

mse2 = 1 / 200 * np.sum(y2 - y_hat2)** 2
print("MSE =", mse2)

MSE = 0.25065258
